# Generated by Django 2.2.28 on 2024-03-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMealMate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
