# Generated by Django 2.2.28 on 2024-03-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyMealMate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profilePic',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
