# Generated by Django 2.2.28 on 2024-03-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMealMate', '0002_auto_20240322_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
