# Generated by Django 2.2.28 on 2024-03-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMealMate', '0002_auto_20240305_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='default_profile.jpg', upload_to='profile_images'),
        ),
    ]
