# Generated by Django 2.2.28 on 2024-03-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMealMate', '0003_auto_20240306_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, default='default_profile.jpg', upload_to='meal_images'),
        ),
    ]
