# Generated by Django 2.2.28 on 2024-03-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMealMate', '0007_auto_20240310_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(max_length=30),
        ),
    ]
