# Generated by Django 2.2.28 on 2024-03-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyMealMate', '0003_auto_20240305_1703'),
        ('MyMealMate', '0011_meal_user'),
    ]

    operations = [
    ]
